# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_article_drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishable',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
